### ISSUE TITLE
Let me opt-in to repos that have the WWLTW chore added automatically

### ISSUE THREAD

**Issue by jchesterpivotal** [oliverswitzer/wwltw-for-pivotal-tracker#1]
I've been getting many emails of the form "Huh? What is this? Why did you add this to our backlog?"

**Comment by oliverswitzer** [comment]
Finally got time to start this: https://www.pivotaltracker.com/story/show/141491873 (you have to be logged in to your @pivotal.io account to see the backlog)

**Comment by oliverswitzer** [comment]
Fixed as a part of the [1.5.0 release](https://github.com/oliverswitzer/wwltw-for-pivotal-tracker/releases/tag/1.5.0).
